application:
  name: order-service #serviceId o chiave di registrazione
  title: Order Service
  version: 1.0.0

server:
  port: 8082
  servlet:
    context-path: /order-service # New Url "host:port/user-service" used from gateway to routing request to this service
  instance:
    hostname: localhost

spring:
  application:
    name: order-service  #name of the application
    version: 1.0.0

  main:
    banner-mode: "console"
    log-startup-info: true

  banner:
    location: classpath:banner.md
  output:
    ansi:
      enabled: always
  profiles:
    active: development

  datasource: #Database configuration
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #JPA configuration
    hibernate:
      ddl-auto: update #update the schema
    show-sql: true #show SQL queries


  jackson:
    serialization.indent_output: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard

logging:  #logging configuration
  level:
    com.example: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.hibernate.orm.jdbc.bind: TRACE #vedo anche i parametri passati nelle query

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #reference URL to registry on Eureka server
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name} #instance ID

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# Local Url dato dalla Server Registry nella sua Dashboard: http://host.docker.internal:8082/api/orders