application:
  name: service-registry
  title: Server Registry
  version: 1.0.0

server:
  port: 8761
  instance:
    hostname: localhost

spring:
  application:
    name: service-registry  #custom name for eureka server
    version: 1.0.0
  main:
    banner-mode: "console"
    log-startup-info: true
  banner:
    location: classpath:banner.md
  output:
    ansi:
      enabled: always
  profiles:
    active: development

eureka: #Eureka server configuration
  instance:
    hostname: localhost
    prefer-ip: true
  client:
    register-with-eureka: false #do not register with Eureka
    fetch-registry: false #do not fetch the registry from Eureka
    #enable-self-preservation: false #disable self-preservation
    #wait-time-in-ms-when-sync-empty: 0 #wait time in milliseconds when the registry is empty
    service-url:
      defaultZone: http://${server.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health  # "*" #expose all endpoints
  endpoint: #Actuator endpoints configuration
    health:
      show-details: always #show details of the health endpoint