#
# Questo file YAML configura il tuo API Gateway per gestire le richieste indirizzate
# ai servizi utente e ordini, con funzionalità di bilanciamento del carico, registrazione
# su Eureka e sicurezza di base disabilitata.
#
application:
  name: api-gateway
  title: API Gateway #title of the application
  version: 1.0.0     #version of the application

server:
  port: 8080
  instance:
   hostname: localhost
 #  serviceUrl:
 #    defaultZone: http://${server.instance.hostname}:${server.port}/eureka/ #reference to the Eureka server

spring:
  application:
    name: api-gateway #name of the application
    version: 1.0.0
  main:
    banner-mode: "console"
    log-startup-info: true
  banner:
    location: classpath:banner.md
  output:
    ansi:
      enabled: always
  profiles:
    active: development
  cloud:  #Spring Cloud Gateway configuration
    gateway:
      discovery: #Service discovery configuration\
        locator: #Service locator configuration
          enabled: true
          lower-case-service-id: true #convert service id to lowercase
      routes:
        - id: user-service
          uri: lb://USER-SERVICE #uri of the service
          predicates:
            - Path=/user-service/**  #- Path=/users/** ; Path gateway =[user-service] e api microservizio =[/api/users/1] => 'order-service/api/users/1'
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE #uri of the service
          predicates: #
            - Path=/order-service/**  #path of the route
          filters:
            - StripPrefix=1 #strip the prefix from the request
    loadbalancer:
      ribbon:
        enabled: true
logging:
  level:
    com.example: INFO
    org.springframework.web: INFO
    org.hibernate.orm.jdbc.bind: INFO #TRACE vedo anche i parametri passati nelle query
    org.springframework.cloud.gateway: TRACE #log level for Spring Cloud Gateway

security:
  basic:
    enabled: false #disable basic authentication

eureka: #Eureka server configuration
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #reference to the Eureka server
  instance:
    prefer-ip-address: true #prefer IP address over hostname for registration on Eureka server and each instance of the service will have a unique IP address of Eureka Server.

management:
  endpoints:
    web:
      exposure:
        include: info,health  # "*" #expose all endpoints
  endpoint: #Actuator endpoints configuration
    health:
      show-details: always #show details of the health endpoint

#Custom Properties
#token:
#  signing: ## SECRET_KEY=f621d0dBa91e2c270c0Ea38v59W996104eA6dm724942c90M
#    key: ${SECRET_KEY}